### ISSUE TITLE
How To Use This? For What?

### ISSUE THREAD

**Issue by Maco1800** [Naseband/SAMP-MapDrawer2D#1]
I Have Some Doubts
1. Is Its Used By Mipmap Lively Or Just Get A Print Out Of Map?
2. What Is The Use Of This?

**Comment by Naseband** [comment]
It generates a view of the current objects created in ColAndreas. ColAndreas just holds the collision info for objects, so it's not an actual render of the real map.

I used it a few times to visualize all custom objects on my server (ie. islands), create top-down views for derby maps or check for holes in large custom maps (this could also be done in the old school MapEditors that have a collision view). But for the most part it's just something to play around with.

I also made a 3D version of it:
https://i.imgur.com/Hcj47RI.jpg

**Comment by Maco1800** [comment]
Ok thanks
